"""Added cascade delete-orphan to relationships

Revision ID: a8995b83cab8
Revises: 1778e15f7bc8
Create Date: 2024-08-21 09:58:38.043289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8995b83cab8'
down_revision = '1778e15f7bc8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_enrollment_course_id', 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key('fk_enrollment_student_id', 'student', ['student_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
